SELECT 
    COALESCE(N.CUST_ID, O.CUST_ID) AS CUST_ID,
    CASE 
        WHEN N.CUST_ID IS NOT NULL AND O.CUST_ID IS NOT NULL AND N.CUST_CITY = O.CUST_CITY THEN 'UPDATE'
        WHEN O.CUST_ID IS NULL THEN 'INSERT'
        WHEN N.CUST_ID IS NULL THEN 'DELETE'
    END AS Action
FROM 
    CustomerInfoNew N
FULL OUTER JOIN 
    CustomerInfoOld O ON N.CUST_ID = O.CUST_ID;